### ISSUE TITLE
Lib doesn't seem to work

### ISSUE THREAD

**Issue by kramer65** [libyal/libpff#27]
So after successfully compiling and installing the lib onto my Ubuntu 16.04 machine, I now try to use the library with Python. But I'm having a hard time doing that:

```
>>> import pypff
>>> pff_file = pypff.file()
>>> pff_file.open("backup.pst")
>>> pff_file.get_number_of_items()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pff_file.get_number_of_items()
AttributeError: 'pypff.file' object has no attribute 'get_number_of_items'
>>> pff_file.number_of_items
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pff_file.number_of_items
AttributeError: 'pypff.file' object has no attribute 'number_of_items'
>>> pff_file.get_item(0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pff_file.get_item(0)
AttributeError: 'pypff.file' object has no attribute 'get_item'
>>> pff_file.items
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    pff_file.items
AttributeError: 'pypff.file' object has no attribute 'items'
```

Any idea what might be wrong here?

Maybe this helps to get some insight:

```
>>> for i in dir(pff_file): print i
...
__class__
__delattr__
__doc__
__format__
__getattribute__
__hash__
__init__
__new__
__reduce__
__reduce_ex__
__repr__
__setattr__
__sizeof__
__str__
__subclasshook__
ascii_codepage
close
get_ascii_codepage
get_number_of_recovered_items
get_root_folder
get_size
open
open_file_object
recover_items
set_ascii_codepage
signal_abort
size
```

**Comment by joachimmetz** [comment]
https://github.com/libyal/libpff/issues/2

**Comment by kramer65** [comment]
That is a pity. The lack of Python support currently renders the lib useless for me (I really appreciate you guys doing this though). 

Is there any ETA for the Python bindings?

**Comment by joachimmetz** [comment]
I'll have a look to see if I can get another experimental release going, with limited Python binding support.
